workflows:
  version: 2
  build-deploy:
    jobs:
      - build
          context: paragres

version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Install Python deps
          command: |
            pip install virtualenv
            tox
